### ISSUE TITLE
load pre-trained weights

### ISSUE THREAD

**Issue by YYmmx21** [paplhjak/Facial-Age-Estimation-Benchmark#15]
Hello, how to load 'resnet50-imdb-em-cnn.pt' into the model？

**Comment by paplhjak** [comment]
Hello,
The model you are referencing is a JIT scripted backbone. To load it, use the following in your configuration file:

```
model:
  architecture: "jit"
  path: "resnet50-imdb-em-cnn.pt"
  nr_features: 2048
  backbone_trainable: True
  input_size: [256, 256]
```
For more information, please see [doc/backbone_support.md](https://github.com/paplhjak/Facial-Age-Estimation-Benchmark/blob/main/doc/backbone_support.md).
